server:
  port: 8080

spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
  security:
    enabled: false
    #oauth2:
      #resourceserver:
        #jwt:
          #issuer-uri: YOUR_ISSUER_URI
  jmx:
    enabled: true
    exposure:
      include: "*"
    admin:
      enabled: true
      jmx-name: spring-gateway:8080


management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  security:
    enabled: false
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
